package demo;
// Generated Jul 9, 2012 9:09:31 PM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int eid;
     private String ename;
     private String salary;

    public Employee() {
    }

	
    public Employee(int eid) {
        this.eid = eid;
    }
    public Employee(int eid, String ename, String salary) {
       this.eid = eid;
       this.ename = ename;
       this.salary = salary;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }




}


